//@version=4
study("Inside Bar Pattern")

// Input Parameters
ib_length = input(title="Inside Bar Length", type=input.integer, defval=5, minval=1)

// Calculate Inside Bar
prev_high = highest(high, ib_length+1)
prev_low = lowest(low, ib_length+1)
inside_bar = high < prev_high and low > prev_low

// Plot Inside Bar
plotshape(inside_bar, title="Inside Bar", style=shape.circle, color=color.green, transp=0, location=location.bottom)

// Alert on Inside Bar
alertcondition(inside_bar, title="Inside Bar", message="Inside Bar Detected")